### PR TITLE
Fix/stone localisation

### PR DESCRIPTION
**Pull request by cerka**
stone localisation is fixed for `fr` and `en` and now correctly detect stones (at least the first one i'm only lvl 14 to test)
it may/will be buggy on others, a reference is needed in `Necrosis/Locales/Functions-**.lua`: `Necrosis.Translation.StoneRank`
and i'm not speaking them so please contribution is welcome

### CODE REVIEW

**Comment by Xerxes13** [comment]
doesnt't work for me (see #22 )

**Comment by froggiton** [comment]
for the German Version it must be
`Necrosis.Translation.StoneRank = {
	["Minor"] = "schwach",
	["Major"] = "gering",
	["Lesser"] = "gro/195/159",
	["Greater"] = "erheblich"
}`

i think /195/159 is ß ?
if not, please correct this /195/159

**Comment by cerka** [comment]
thank you i'll patch it tonight

**Comment by froggiton** [comment]
change in dialog-de.lua and not in functions-de.lua ?
for en and fr it was in functions-xx.lua ^^

**Comment by ADeeds** [comment]
On this version, Healthstone seems to work correctly but soulstone doesn't (en)

**Comment by cerka** [comment]
i didn't fixed the starting id for soulstone yet (in `spells.lua`)
i'll try to do it this afternoon or tomorrow

**Comment by ADeeds** [comment]
@cerka Well that explains it :) The SS button displayed but the right-click didn't function.

Although I just learned Lesser Healthstone and the right-click no longer works on the healthstone button. It looks like maybe the ranks are in the wrong order in the code?

I think it should be Minor -> Lesser -> (regular) -> Great -> Major, but the rankToStone and stoneToRank functions order them differently (eg https://github.com/robert388/Necrosis-classic/blob/84d345c3e9ef2cf2501f487419911622af33a378/Necrosis/Necrosis.lua#L2140).

**Pull request merged**
