### PR TITLE
fix timer for banish

### PR DESCRIPTION
**Pull request by pelletjl**
Revert breaking changes, cleanup mana cost localization, and fix duration of banish timer.

### CODE REVIEW

**Comment by tekHudson** [comment]
Can we please separate this into multiple PRs. I am just coming to this code base as I noticed it wasn't being updated by author. I will need time to familiarize myself with the codebase before I can do large refactor PRs
1. Fix banish timer
2. Code refactors (which is great btw)

**Comment by pelletjl** [comment]
Pulled the localization refactor into a new pull request. Both changes depend on reverting previous branch pull since i haven't been able to track down where in that chain to fix the timer breaking changes.

**Comment by tekHudson** [comment]
Let's get that other stuff merged first. I can't even figure out what is going on in here. :D 

Thanks so much for you effort!

**Comment by pelletjl** [comment]
Superseded by #103

**Pull request closed without merging**
